/// <reference path="coachboard.ts" />
/// <reference path="vector.ts" />
/// <reference path="touchevent.ts"/>
/// <reference path="idrawable.ts"/>
/// <reference path="line.ts"/>
/// <reference path="rectangle.ts"/>
/// <reference path="freeline.ts"/>
/// <reference path="shapefactory.ts"/>
/// <reference path="raakstorage.ts"/>
/// <reference path="playfield.ts"/>
/// <reference path="arrow.ts"/>
/// <reference path="icon.ts" />