/// <reference path="CoachBoard.ts" />
/// <reference path="vector.ts" />
/// <reference path="touchevent.ts"/>
/// <reference path="IDrawable.ts"/>
/// <reference path="Line.ts"/>
/// <reference path="Rectangle.ts"/>
/// <reference path="FreeLine.ts"/>
/// <reference path="ShapeFactory.ts"/>
/// <reference path="RaakStorage.ts"/>
/// <reference path="PlayField.ts"/>